# Configurações do Ambiente de Produção (prod)
replicaCount: 3  # Alta disponibilidade (HA) em produção com 3 réplicas

image:
  repository: nginxinc/nginx-unprivileged
  tag: "1.27-alpine"

ingress:
  hosts:
    - host: prod-sample.local
      paths:
        - path: /
          pathType: Prefix

# Estratégia de Canary mais conservadora para Produção
rollout:
  steps:
    - setWeight: 10
    - pause:
        duration: 30s  # Pausa mais longa para monitorar erros antes de aumentar a carga
    - setWeight: 50
    - pause:
        duration: 30s

# Recursos mais elevados em Produção para suportar maior tráfego
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# HPA Ativado em Produção
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75