apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  template.rollout-rollback: |
    message: |
      ⚠️ Alerta de Rollback no Argo Rollouts!
      A aplicação {{.app.metadata.name}} sofreu rollback automático devido à falha nos testes de análise de métricas de sucesso do Prometheus.
  trigger.on-rollback: |
    - when: app.status.health.status == 'Degraded'
      send: [rollout-rollback]
