apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      {{- include "sample-app.selectorLabels" . | nindent 6 }}
  strategy:
    canary:
      canaryService: {{ include "sample-app.fullname" . }}-canary
      stableService: {{ include "sample-app.fullname" . }}
      trafficRouting:
        nginx:
          stableIngress: {{ include "sample-app.fullname" . }}
      steps:
        {{- toYaml .Values.rollout.steps | nindent 8 }}
      analysis:
        templates:
          - templateName: {{ include "sample-app.fullname" . }}-success-rate
        args:
          - name: service-name
            value: {{ include "sample-app.fullname" . }}-canary
  template:
    metadata:
      labels:
        {{- include "sample-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints.enabled }}
      topologySpreadConstraints:
        - maxSkew: {{ .Values.topologySpreadConstraints.maxSkew }}
          topologyKey: {{ .Values.topologySpreadConstraints.topologyKey | quote }}
          whenUnsatisfiable: {{ .Values.topologySpreadConstraints.whenUnsatisfiable | quote }}
          labelSelector:
            matchLabels:
              {{- include "sample-app.selectorLabels" . | nindent 14 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
