{{- if .Values.sealedSecret.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "sample-app.fullname" . }}-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
  annotations:
    # namespace-wide: false garante validação criptográfica por namespace (proteção contra replay attack)
    sealedsecrets.bitnami.com/namespace-wide: "false"
spec:
  encryptedData:
    # Gere o payload com:
    #   echo -n 'senha' | kubectl create secret generic db-creds \
    #     --dry-run=client --from-file=DB_PASSWORD=/dev/stdin -o yaml | \
    #     kubeseal --controller-name=sealed-secrets --controller-namespace=kube-system \
    #     --format yaml
    DB_PASSWORD: {{ .Values.sealedSecret.encryptedDBPassword | quote }}
  template:
    metadata:
      name: {{ include "sample-app.fullname" . }}-db-credentials
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
