# Configurações do Ambiente de Desenvolvimento (dev)
replicaCount: 1  # Apenas 1 réplica para economizar recursos no cluster de dev

image:
  repository: nginxinc/nginx-unprivileged
  tag: "1.27-alpine"

ingress:
  hosts:
    - host: dev-sample.local
      paths:
        - path: /
          pathType: Prefix

# Estratégia de Canary mais rápida para desenvolvimento
rollout:
  steps:
    - setWeight: 50
    - pause:
        duration: 5s